#[
autogenerated by docgen
loc: /home/runner/work/nodejs/nodejs/src/nodejs/jsassert.nim(132, 1)
rdoccmd: 
]#
import "/home/runner/work/nodejs/nodejs/src/nodejs/jsassert.nim"
{.line: ("/home/runner/work/nodejs/nodejs/src/nodejs/jsassert.nim", 132, 1).}:
  import std/[jsffi, jsre]
  requireAssert()
  block:
    let tracker: CallTracker = newCallTracker()
    doAssert tracker.report() is JsObject
    tracker.verify()
  block:
    doAssert newAssertionError() == """{"generatedMessage":true,"code":"ERR_ASSERTION"}""".cstring
    doAssert newAssertionError("message".cstring, 1.cint, 2.cint, "strictEqual".cstring) == """{"generatedMessage":false,"code":"ERR_ASSERTION","actual":1,"expected":2,"operator":"strictEqual"}""".cstring
    deepStrictEqual(42.cint, 42.cint, "message".cstring)
    notDeepStrictEqual(666.cint, 42.cint, "message".cstring)
    strictEqual(666.cint, 666.cint, "message".cstring)
    ok(true, "message".cstring)
    let rege: RegExp = newRegExp("[0-9]", "i")
    doesNotMatch("abcde".cstring, rege, "message".cstring)

