# autogenerated by docgen
# source: /home/runner/work/nodejs/nodejs/src/nodejs/jsasynchooks.nim
# rdoccmd: 
import "/home/runner/work/nodejs/nodejs/docs/nimcache/runnableExamples/jsasynchooks_examples_1.nim"
