#[
autogenerated by docgen
loc: /home/runner/work/nodejs/nodejs/src/nodejs/jsasynchooks.nim(15, 1)
rdoccmd: 
]#
import "/home/runner/work/nodejs/nodejs/src/nodejs/jsasynchooks.nim"
{.line: ("/home/runner/work/nodejs/nodejs/src/nodejs/jsasynchooks.nim", 15, 1).}:
  requireAsynchooks()
  echo triggerAsyncId()
  echo executionAsyncId()

