#[
autogenerated by docgen
loc: /home/runner/work/nodejs/nodejs/src/nodejs/jsfs.nim(385, 1)
rdoccmd: 
]#
import "/home/runner/work/nodejs/nodejs/src/nodejs/jsfs.nim"
{.line: ("/home/runner/work/nodejs/nodejs/src/nodejs/jsfs.nim", 385, 1).}:
  requireFs()
  touchFileSync("touched.txt")
  writeFileSync("touched.txt".cstring, "data".cstring)
  appendFileSync("touched.txt".cstring, "\nmore data".cstring)
  renameSync("touched.txt".cstring, "renamed.txt".cstring)
  chmodSync("renamed.txt".cstring, 0o777)
  copyFileSync("renamed.txt".cstring, "copied.txt".cstring)
  let data: cstring = readFileSync("renamed.txt")
  rmSync("renamed.txt".cstring)
  rmSync("copied.txt".cstring)
  echo mkdtempSync("test".cstring)
  # mkdirSync("/tmp/somerandomame".cstring, recursive = true)

