#[
autogenerated by docgen
loc: /home/runner/work/nodejs/nodejs/src/nodejs/jsfs.nim(399, 17)
rdoccmd: -r:off
]#
import "/home/runner/work/nodejs/nodejs/src/nodejs/jsfs.nim"
import nodejs/jsbuffer
requireFs()
requireBuffer()
proc example(error: int; data: Buffer) = echo data
readFile("somefile.ext", example)
