#[
autogenerated by docgen
loc: /home/runner/work/nodejs/nodejs/src/nodejs/jspath.nim(56, 1)
rdoccmd: 
]#
import "/home/runner/work/nodejs/nodejs/src/nodejs/jspath.nim"
{.line: ("/home/runner/work/nodejs/nodejs/src/nodejs/jspath.nim", 56, 1).}:
  requirePath()
  echo delimiter
  doAssert basename("/foo/bar/baz".cstring) == "baz".cstring
  doAssert dirname("/foo/bar/baz/file.ext".cstring) == "/foo/bar/baz".cstring
  doAssert extname("/foo/bar/baz/file.ext".cstring) == ".ext".cstring
  doAssert isAbsolute("/foo/bar/baz/file.ext".cstring)
  doAssert normalize("/foo/bar/baz/file.ext".cstring) == "/foo/bar/baz/file.ext".cstring
  doAssert normalize("/foo/bar/baz/file.ext".cstring) == "/foo/bar/baz/file.ext".cstring
  doAssert relative("/foo/bar/baz/file.ext".cstring, "/x/".cstring) == "../../../../x".cstring
  doAssert resolve("/foo/bar/baz/file.ext".cstring) == "/foo/bar/baz/file.ext".cstring
  doAssert toNamespacedPath("/foo/bar/baz/file.ext".cstring) == "/foo/bar/baz/file.ext".cstring
  doAssert join("foo".cstring, "bar".cstring, "file.ext".cstring) == "foo/bar/file.ext".cstring
  doAssert "folder".cstring / "file.ext".cstring == "folder/file.ext".cstring

