#[
autogenerated by docgen
loc: /home/runner/work/nodejs/nodejs/src/nodejs/jsperfhooks.nim(43, 1)
rdoccmd: 
]#
import "/home/runner/work/nodejs/nodejs/src/nodejs/jsperfhooks.nim"
{.line: ("/home/runner/work/nodejs/nodejs/src/nodejs/jsperfhooks.nim", 43, 1).}:
  requirePerfhooks()
  mark()
  clearMarks()
  echo jsnow()

