# autogenerated by docgen
# source: /home/runner/work/nodejs/nodejs/src/nodejs/jsperfhooks.nim
# rdoccmd: 
import "/home/runner/work/nodejs/nodejs/docs/nimcache/runnableExamples/jsperfhooks_examples_1.nim"
