# autogenerated by docgen
# source: /home/runner/work/nodejs/nodejs/src/nodejs/jsprocess.nim
# rdoccmd: 
import "/home/runner/work/nodejs/nodejs/docs/nimcache/runnableExamples/jsprocess_examples1.nim"
