# autogenerated by docgen
# source: /home/runner/work/nodejs/nodejs/src/nodejs/jsprocess.nim
# rdoccmd: -r:off
import "/home/runner/work/nodejs/nodejs/docs/nimcache/runnableExamples/jsprocess_examples_2.nim"
