#[
autogenerated by docgen
loc: /home/runner/work/nodejs/nodejs/src/nodejs/jsprocess.nim(159, 17)
rdoccmd: -r:off
]#
import "/home/runner/work/nodejs/nodejs/src/nodejs/jsprocess.nim"
{.line: ("/home/runner/work/nodejs/nodejs/src/nodejs/jsprocess.nim", 159, 17).}:
  requireProcess()
  echo argv ## Read Command Line Arguments as seq[cstring]

