#[
autogenerated by docgen
loc: /home/runner/work/nodejs/nodejs/src/nodejs/jsprocess.nim(142, 1)
rdoccmd: 
]#
import "/home/runner/work/nodejs/nodejs/src/nodejs/jsprocess.nim"
requireProcess()
doAssert not hasUncaughtExceptionCaptureCallback()
echo cwd()
emitWarning("Information is power. But like all power, there are those who want to keep it for themselves".cstring)
echo getegid()
echo getgroups()
echo getuid()
echo hrtime()
echo hrtimeBigint()
echo reportWriteReport()
echo uptimeProcess()
chdir("/tmp".cstring)
if false:
  abort()
  disconnect()
  exit(code = 0.cint)
