#[
autogenerated by docgen
loc: /home/runner/work/nodejs/nodejs/src/nodejs/jspunycode.nim(27, 1)
rdoccmd: 
]#
import "/home/runner/work/nodejs/nodejs/src/nodejs/jspunycode.nim"
requirePunycode()
const str = "hello".cstring
doAssert decode(str) == "㗁㖼㖶".cstring
doAssert encode(str) == "hello-".cstring
doAssert toASCII(str) == "hello".cstring
doAssert toUnicode(str) == "hello".cstring
doAssert ucs2Decode(str) == @[104.cint, 101, 108, 108, 111]
doAssert ucs2Encode(@[104.cint, 101, 108, 108, 111]) == "hello".cstring
