#[
autogenerated by docgen
loc: /home/runner/work/nodejs/nodejs/src/nodejs/jsreadline.nim(64, 1)
rdoccmd: 
]#
import "/home/runner/work/nodejs/nodejs/src/nodejs/jsreadline.nim"
{.line: ("/home/runner/work/nodejs/nodejs/src/nodejs/jsreadline.nim", 64, 1).}:
  import std/jsffi, nodejs/jsprocess
  requireProcess()
  requireReadline()
  block:
    doAssert clearLine()
    doAssert clearScreenDown()
    doAssert cursorTo(x = 0.cint, y = 0.cint)
    doAssert moveCursor(dx = 0.cint, dy = 0.cint)
  block:
    let rl: Readline = newReadline()
    rl.setPrompt(">>>".cstring)
    # doAssert rl.getPrompt() == ">>>".cstring
    doAssert rl.getCursorPos() is JsObject
    rl.pause()
    rl.resume()
    rl.write("data".cstring)
    rl.close()
    # echo rl.line()
    # echo rl.cursor()

