# autogenerated by docgen
# source: /home/runner/work/nodejs/nodejs/src/nodejs/jsreadline.nim
# rdoccmd: -r:off
import "/home/runner/work/nodejs/nodejs/docs/nimcache/runnableExamples/jsreadline_examples_2.nim"
