# autogenerated by docgen
# source: /home/runner/work/nodejs/nodejs/src/nodejs/jsreadline.nim
# rdoccmd: 
import "/home/runner/work/nodejs/nodejs/docs/nimcache/runnableExamples/jsreadline_examples_1.nim"
