#[
autogenerated by docgen
loc: /home/runner/work/nodejs/nodejs/src/nodejs/jsreadline.nim(85, 17)
rdoccmd: -r:off
]#
import "/home/runner/work/nodejs/nodejs/src/nodejs/jsreadline.nim"
{.line: ("/home/runner/work/nodejs/nodejs/src/nodejs/jsreadline.nim", 85, 17).}:
  import nodejs/jsprocess
  requireProcess()
  requireReadline()
  let rl = newReadline()
  echo rl.line()

