#[
autogenerated by docgen
loc: /home/runner/work/nodejs/nodejs/src/nodejs/jsugar.nim(147, 3)
rdoccmd: 
]#
import "/home/runner/work/nodejs/nodejs/src/nodejs/jsugar.nim"
import std/jsconsole
jsFmt:
  foo := "platypus".cstring
  bar := "capybara".cstring
  console.log fmt("foo ${foo} bar ${bar} baz ${8 + 1} !?".cstring)
