#[
autogenerated by docgen
loc: /home/runner/work/nodejs/nodejs/src/nodejs/jsugar.nim(173, 3)
rdoccmd: 
]#
import "/home/runner/work/nodejs/nodejs/src/nodejs/jsugar.nim"
{.line: ("/home/runner/work/nodejs/nodejs/src/nodejs/jsugar.nim", 173, 3).}:
  block:
    var example: seq[int]
    for i in backoff(1, 9): example.add i
    doAssert example == @[1, 2, 4, 8]
  block:
    var example: seq[float]
    for i in backoff(1.0, 9.9): example.add i
    doAssert example == @[1.0, 2.0, 4.0, 8.0]

