# autogenerated by docgen
# source: /home/runner/work/nodejs/nodejs/src/nodejs/jsugar.nim
# rdoccmd: 
import "/home/runner/work/nodejs/nodejs/docs/nimcache/runnableExamples/jsugar_examples1.nim"
import "/home/runner/work/nodejs/nodejs/docs/nimcache/runnableExamples/jsugar_examples2.nim"
import "/home/runner/work/nodejs/nodejs/docs/nimcache/runnableExamples/jsugar_examples3.nim"
import "/home/runner/work/nodejs/nodejs/docs/nimcache/runnableExamples/jsugar_examples4.nim"
