#[
autogenerated by docgen
loc: /home/runner/work/nodejs/nodejs/src/nodejs/jsugar.nim(135, 3)
rdoccmd: 
]#
import "/home/runner/work/nodejs/nodejs/src/nodejs/jsugar.nim"
{.line: ("/home/runner/work/nodejs/nodejs/src/nodejs/jsugar.nim", 135, 3).}:
  doAssert daysBetweenYears(1970, 2020) == 18262
  doAssert daysBetweenYears(2000, 2020) == 7305
  doAssert daysBetweenYears(1970, 1970) == 0
  doAssert daysBetweenYears(2020, 2020) == 0
  doAssert daysBetweenYears(1999, 2000) == 365

