#[
autogenerated by docgen
loc: /home/runner/work/nodejs/nodejs/src/nodejs/jsugar.nim(155, 3)
rdoccmd: 
]#
import "/home/runner/work/nodejs/nodejs/src/nodejs/jsugar.nim"
{.line: ("/home/runner/work/nodejs/nodejs/src/nodejs/jsugar.nim", 155, 3).}:
  var x = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
  shuffle(x)
  doAssert x != [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

