# autogenerated by docgen
# source: /home/runner/work/nodejs/nodejs/src/nodejs/jsugar.nim
# rdoccmd: 
import "/home/runner/work/nodejs/nodejs/docs/nimcache/runnableExamples/jsugar_examples_1.nim"
import "/home/runner/work/nodejs/nodejs/docs/nimcache/runnableExamples/jsugar_examples_2.nim"
import "/home/runner/work/nodejs/nodejs/docs/nimcache/runnableExamples/jsugar_examples_3.nim"
import "/home/runner/work/nodejs/nodejs/docs/nimcache/runnableExamples/jsugar_examples_4.nim"
import "/home/runner/work/nodejs/nodejs/docs/nimcache/runnableExamples/jsugar_examples_5.nim"
