#[
autogenerated by docgen
loc: /home/runner/work/nodejs/nodejs/src/nodejs/jsurl.nim(76, 1)
rdoccmd: 
]#
import "/home/runner/work/nodejs/nodejs/src/nodejs/jsurl.nim"
{.line: ("/home/runner/work/nodejs/nodejs/src/nodejs/jsurl.nim", 76, 1).}:
  requireUrl()
  block:
    let u: URL = newURL("https://user:pass@sub.example.com:8080/p/a/t/h?query=string#hash".cstring)
    doAssert u.toCstring is cstring
    doAssert u.len == 64
    # echo u.toJSON
  block:
    let para: URLSearchParams = newURLSearchParams("?user=abc&query=xyz".cstring)
    doAssert para.toCstring is cstring
    para.add "key".cstring, "value".cstring
    para.sort()
    doAssert para.hasKey "key".cstring
    doAssert para.keys == @["key".cstring, "query", "user"]
    doAssert para.values == @["value".cstring, "xyz", "abc"]
    doAssert para.get("key".cstring) == "value".cstring
    doAssert para.getAll("key".cstring) == @["value".cstring]
    doAssert $para == "key=value&query=xyz&user=abc"
    para.delete "key".cstring
  block:
    doAssert domainToASCII("中文.com".cstring) == "xn--fiq228c.com".cstring
    doAssert domainToUnicode("xn--fiq228c.com".cstring) == "中文.com".cstring
    when defined(linux):  ## May or may not be OS and platform dependent.
      doAssert fileURLToPath("file:///C:/path/".cstring) == "/C:/path/".cstring

