name: Build
on:
  push:
    paths:
      - 'src/**.nim'
      - '.github/workflows/*.yml'
      - '.github/workflows/*.yaml'
      - '.gitignore'

jobs:
  build:
    if: |
      !contains(github.event.head_commit.message, '[skip ci]')
    strategy:
      fail-fast: true
      matrix:
        platform: [ubuntu-latest, windows-latest]
    name: ${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2

    - uses: jiro4989/setup-nim-action@v1
      with:
        nim-version: 'devel'
        no-color: true  # --noColor

    # - uses: juancarlospaco/nimpretty-action@main
    #   with:
    #     folders: "src"

    # https://developer.ibm.com/languages/node-js/blogs/nodejs-15-release-blog
    - name: Generate Documentation (Linux)
      if: runner.os == 'Linux'
      run: |
        export NODE_OPTIONS=--unhandled-rejections=warn
        nim doc -b:js -d:nodejs --project --experimental:strictFuncs --styleCheck:hint --outdir:docs src/nodejs.nim
        rm --verbose docs/nodejs/*.idx
        rm --verbose --force --recursive docs/nimcache/*.*
        rm --verbose --force --recursive docs/nimcache/runnableExamples/*.*
        mv --verbose docs/nodejs.html docs/index.html

    - name: Commit Docs
      uses: EndBug/add-and-commit@v4  # Commit everything to Git repo
      with:
        add: 'docs'
        force: true
        message: 'Fully Automated Luxury Nim'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
