name: Welcome New Users

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: |
          # Welcome ${{github.actor}} :tada:
          Congrats for your first issue!, please provide a minimal code example that reproduces the bug!.
          Reports with full repro code and descriptive detailed information will be fixed faster.

        pr-message: |
          # Welcome ${{github.actor}} :tada: 
          Congrats for your first Pull Request!, we will review your contributions very soon, and likely merge it!.
