name: Welcome New Users

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: |
          # Welcome ${{github.actor}}
          - **Remember to :star: Star the project on GitHub!.**
          - **Congrats for your first issue!, please provide a minimal code example that reproduces the :bug: Bug!.**
            Reports with full repro code and descriptive detailed information will be fixed faster.
          - [Please, keep in mind there is ZERO FUNDING for the project!, we have no sponsors, no company behind, no dev team,
            :heart: Send crypto today to speed up development!](https://gist.github.com/juancarlospaco/37da34ed13a609663f55f4466c4dbc3e)

        pr-message: |
          # Welcome ${{github.actor}}
          - **Remember to :star: Star the project on GitHub!.**
          - **Congrats for your first Pull Request!, we will review your contributions very soon, and likely merge it!.**
            Pull Requests with detailed description of the changes and documentation on the code will be merged faster.
          - [Please, keep in mind there is ZERO FUNDING for the project!, we have no sponsors, no company behind, no dev team,
            :heart: Send crypto today to speed up development!](https://gist.github.com/juancarlospaco/37da34ed13a609663f55f4466c4dbc3e)
